// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWVZ-eqXCEMkkgs6aTLIygBIzB4f-UIfY',
    appId: '1:1061553314181:web:77fb5bc52957890b4dccec',
    messagingSenderId: '1061553314181',
    projectId: 'fruit-hub-79975',
    authDomain: 'fruit-hub-79975.firebaseapp.com',
    storageBucket: 'fruit-hub-79975.firebasestorage.app',
    measurementId: 'G-DNCN132W2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyduR0i8MesVa5PSSoPeJleFQyR6MAfUM',
    appId: '1:1061553314181:android:4b4c8078f7a540a84dccec',
    messagingSenderId: '1061553314181',
    projectId: 'fruit-hub-79975',
    storageBucket: 'fruit-hub-79975.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnjbVeU_uDJychvv6ea3aWPLNYG20XKwg',
    appId: '1:1061553314181:ios:8ceb29abe3e1d6cc4dccec',
    messagingSenderId: '1061553314181',
    projectId: 'fruit-hub-79975',
    storageBucket: 'fruit-hub-79975.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnjbVeU_uDJychvv6ea3aWPLNYG20XKwg',
    appId: '1:1061553314181:ios:8ceb29abe3e1d6cc4dccec',
    messagingSenderId: '1061553314181',
    projectId: 'fruit-hub-79975',
    storageBucket: 'fruit-hub-79975.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWVZ-eqXCEMkkgs6aTLIygBIzB4f-UIfY',
    appId: '1:1061553314181:web:3dae56ebce7f19f64dccec',
    messagingSenderId: '1061553314181',
    projectId: 'fruit-hub-79975',
    authDomain: 'fruit-hub-79975.firebaseapp.com',
    storageBucket: 'fruit-hub-79975.firebasestorage.app',
    measurementId: 'G-Y66BH3P7PF',
  );
}
